-- PROG 202 · Lab 1 — the driver.  Do not edit this file; Sched.hs is the work.
module Main (main) where

import Sched

main :: IO ()
main = case timetable of
  Left err -> putStrLn ("rejected: " ++ err)
  Right ts -> do
    putStrLn $ "sessions         : " ++ show (length ts)
    putStrLn $ "contact minutes  : " ++ show (sum (map duration ts))
    putStrLn   "clashes          :"
    mapM_ (\(a, b) -> putStrLn ("  " ++ render a ++ "  vs  " ++ render b))
          [ p | p@(a, b) <- pairs ts, overlaps a b ]
    putStrLn   "lunch collisions :"
    mapM_ (putStrLn . ("  " ++) . render)
          [ t | d <- [minBound .. maxBound], t <- ts, inWindow (lunch d) t ]
    putStrLn $ "minutes per day  : "
      ++ show [ (d, sum [ duration t | t <- ts, day t == d ])
              | d <- [minBound .. maxBound] ]
