#!/usr/bin/env python3
"""Phase 9: three-address code to LLVM IR.

Weeks 0-6 built eight phases and ended at a register assignment that was
never turned into machine code. `runtime.py` interpreted the TAC instead,
which was the right call for studying garbage collection and the wrong one
for producing a program.

This file finishes the job, and it finishes it by **not writing a back end**.
It emits LLVM IR -- a textual, target-independent assembly language -- and
hands the rest to LLVM:

    cyan  ->  our 8 phases  ->  LLVM IR  ->  [ opt ]  ->  llc  ->  x86-64
                                          \\-> lli (a JIT)

That is the bargain L23 is about. We write a front end; LLVM supplies the
optimiser and every back end it has, and we get x86-64, ARM64, RISC-V and
WebAssembly without writing a line of any of them.

**The one thing to understand about the code below is `alloca`.**

LLVM IR is in SSA form -- every register assigned exactly once. Our TAC is
not: `a = a % b` reassigns `a`, and Week 4 needed phi functions to model
that. Constructing SSA directly in a front end is real work.

So we do not. **Every variable gets a stack slot (`alloca`), and every read
and write becomes a `load` or `store`.** That is trivially correct, produces
appalling IR, and is exactly what clang itself does -- because LLVM's
`mem2reg` pass then promotes those slots to SSA registers and inserts the
phi functions for us, using the dominance-frontier algorithm from Week 4.

**We are not avoiding the hard part. We are calling a library that does it**,
and section 5 of L23 measures what that call is worth.

Supported: `int` and `bool` -- arithmetic, comparisons, `if`, `while`,
calls, recursion. Not supported: arrays and structs, which need a heap and
a garbage collector at the IR level. That is PS 11 Part C.
"""
import subprocess
import sys
import os
from itertools import count

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from lexer import LexError
from parser import parse, ParseError
from typecheck import Checker, TypeError_, INT, BOOL
from tac import TAC, Instr, build_cfg
import live as L


class Unsupported(Exception):
    """A construct this back end declines to lower, said out loud.

    Compare `runtime.py`, which interprets everything: the moment you emit
    real code you have to decide what a value *is*, and `[int]` cannot be an
    `i64`. PS 11 Part C is this exception.
    """


HEADER = """\
; ---- generated by cyanc, CS 211 Week 11 ----
; source language: Cyan.  target: LLVM IR (textual).
target triple = "{triple}"
"""

# Cyan's binary operators, in the order LLVM spells them.
ARITH = {'+': 'add', '-': 'sub', '*': 'mul', '/': 'sdiv', '%': 'srem'}
CMP = {'<': 'slt', '<=': 'sle', '>': 'sgt', '>=': 'sge',
       '==': 'eq', '!=': 'ne'}


class LLVMGen:
    def __init__(self, fn_types):
        self.out = []
        self.n = count()
        self.fn_types = fn_types      # name -> (argtypes, rettype)

    def tmp(self):
        return f"%t{next(self.n)}"

    def emit(self, line):
        self.out.append('  ' + line)

    def label(self, name):
        self.out.append(f"{name}:")

    # ------------------------------------------------------------ helpers
    def slot(self, name):
        """The alloca holding a Cyan variable or TAC temporary."""
        return f"%{name}.addr"

    def load(self, operand):
        """An operand becomes an SSA value: a literal is itself, a variable
        is a load from its stack slot."""
        if isinstance(operand, bool):
            return 'true' if operand else 'false', 'i1'
        if isinstance(operand, int):
            return str(operand), 'i64'
        t = self.tmp()
        self.emit(f"{t} = load i64, ptr {self.slot(operand)}")
        return t, 'i64'

    def store(self, name, value):
        self.emit(f"store i64 {value}, ptr {self.slot(name)}")

    def as_i64(self, value, ty):
        """Comparisons produce i1; everything in our TAC is i64."""
        if ty == 'i64':
            return value
        t = self.tmp()
        self.emit(f"{t} = zext i1 {value} to i64")
        return t

    # -------------------------------------------------------------- driver
    def gen_fn(self, decl, code):
        params = [p for p, _ in decl.params]
        args = ', '.join(f"i64 %{p}.in" for p in params)
        self.out.append(f"define i64 @{decl.name}({args}) {{")
        self.label("entry")

        # Every variable and temporary gets a stack slot. mem2reg will
        # remove almost all of them.
        names = set(params)
        for ins in code:
            names |= L.defs(ins) | L.uses(ins)
        for nm in sorted(names):
            self.emit(f"{self.slot(nm)} = alloca i64")
        for p in params:
            self.emit(f"store i64 %{p}.in, ptr {self.slot(p)}")

        # A label may be the target of a branch, and LLVM requires every
        # basic block to end with a terminator -- so a fall-through into a
        # label needs an explicit `br`.
        labels = {ins.label for ins in code if ins.op == 'label'}
        # True, not False: the `entry` block we are currently inside must be
        # terminated before the first label starts a new block. LLVM requires
        # every basic block to end with a terminator, and falling through is
        # not one -- unlike our TAC, where fall-through is the default.
        need_br = True
        for i, ins in enumerate(code):
            if ins.op == 'label':
                if need_br:
                    self.emit(f"br label %{ins.label}")
                self.label(ins.label)
                need_br = True
                continue
            need_br = self.gen_instr(ins)
        if need_br:
            self.emit("ret i64 0")          # fell off the end
        self.out.append("}")
        self.out.append("")

    def gen_instr(self, ins):
        """Emit one TAC instruction. Returns False if it was a terminator."""
        op = ins.op

        if op == 'const':
            v = 1 if ins.a is True else 0 if ins.a is False else ins.a
            if not isinstance(v, int):
                raise Unsupported(f"non-integer constant {ins.a!r}")
            self.store(ins.dst, v)
        elif op == 'copy':
            v, ty = self.load(ins.a)
            self.store(ins.dst, self.as_i64(v, ty))
        elif op == 'unary':
            v, ty = self.load(ins.b)
            t = self.tmp()
            if ins.a == '-':
                self.emit(f"{t} = sub i64 0, {v}")
            else:                                   # logical not
                z = self.tmp()
                self.emit(f"{z} = icmp eq i64 {v}, 0")
                self.emit(f"{t} = zext i1 {z} to i64")
            self.store(ins.dst, t)
        elif op in ARITH:
            a, _ = self.load(ins.a)
            b, _ = self.load(ins.b)
            t = self.tmp()
            self.emit(f"{t} = {ARITH[op]} i64 {a}, {b}")
            self.store(ins.dst, t)
        elif op in CMP:
            a, _ = self.load(ins.a)
            b, _ = self.load(ins.b)
            c, t = self.tmp(), self.tmp()
            self.emit(f"{c} = icmp {CMP[op]} i64 {a}, {b}")
            self.emit(f"{t} = zext i1 {c} to i64")
            self.store(ins.dst, t)
        elif op == 'goto':
            self.emit(f"br label %{ins.label}")
            return False
        elif op in ('ifz', 'iftrue'):
            v, _ = self.load(ins.a)
            c = self.tmp()
            self.emit(f"{c} = icmp {'eq' if op == 'ifz' else 'ne'} i64 {v}, 0")
            cont = f"cont{next(self.n)}"
            self.emit(f"br i1 {c}, label %{ins.label}, label %{cont}")
            self.label(cont)
        elif op == 'ret':
            if ins.a is None:
                self.emit("ret i64 0")
            else:
                v, ty = self.load(ins.a)
                self.emit(f"ret i64 {self.as_i64(v, ty)}")
            return False
        elif op == 'call':
            argv = []
            for a in ins.b:
                v, ty = self.load(a)
                argv.append(f"i64 {self.as_i64(v, ty)}")
            t = self.tmp()
            self.emit(f"{t} = call i64 @{ins.a}({', '.join(argv)})")
            if ins.dst:
                self.store(ins.dst, t)
        elif op == 'phi':
            raise Unsupported("phi must be destroyed before codegen "
                              "(L10 section 5) -- or left to mem2reg")
        elif op in ('alloc', 'newarr', 'load', 'store', 'getfield',
                    'setfield'):
            raise Unsupported(
                f"'{op}' needs a heap and a collector at the IR level. "
                f"Week 6 built both for the interpreter; PS 11 Part C is "
                f"porting them to LLVM.")
        else:
            raise Unsupported(f"no lowering for opcode '{op}'")
        return True


_TRIPLE = None


def target_triple():
    """The host target, asked once.

    `llvm-config` is a subprocess, and a subprocess costs milliseconds --
    which is more than every other phase of this compiler put together on a
    small program. Uncached, it made the LLVM phase look like 80% of compile
    time in `cyanc --times`, and that number was about process creation, not
    about code generation.
    """
    global _TRIPLE
    if _TRIPLE is not None:
        return _TRIPLE
    try:
        _TRIPLE = subprocess.run(['llvm-config', '--host-target'],
                                 capture_output=True, text=True,
                                 timeout=10).stdout.strip()
    except Exception:
        _TRIPLE = ""
    _TRIPLE = _TRIPLE or "x86_64-pc-linux-gnu"
    return _TRIPLE


def compile_to_llvm(src, want=None, ast=None):
    """Cyan source -> LLVM IR text.

    `ast` may be supplied by a caller that has already parsed and checked --
    `cyanc.py` has. Without it this function re-runs the front end, which is
    correct but makes any phase-timing table nonsense: the LLVM phase then
    includes a second parse and type-check and appears to dominate.
    """
    if ast is None:
        ast = parse(src)
        c = Checker()
        c.check_program(ast)

    decls = [d for d in ast.decls if d.kind == 'Fn']
    fn_types = {d.name: ([t for _, t in d.params], d.ret) for d in decls}

    g = LLVMGen(fn_types)
    g.out.append(HEADER.format(triple=target_triple()))
    for d in decls:
        if want and d.name != want:
            continue
        t = TAC()
        t.gen_fn(d)
        L.check_coverage(t.code)
        g.gen_fn(d, t.code)
    return '\n'.join(g.out)


def main(argv):
    if len(argv) < 2:
        print("usage: llvmgen.py FILE.cy [FN]", file=sys.stderr)
        return 2
    src = open(argv[1]).read()
    want = argv[2] if len(argv) > 2 else None
    try:
        print(compile_to_llvm(src, want))
    except (LexError, ParseError, TypeError_) as e:
        print(f"error: {e}", file=sys.stderr)
        return 1
    except Unsupported as e:
        print(f"error: unsupported: {e}", file=sys.stderr)
        return 3
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv))
